name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt install -y libfuse-dev libcurl4-openssl-dev

    - name: autoreconf
      run: autoreconf --install

    - name: configure
      run: ./configure

    - name: Compile
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
